### ISSUE TITLE
java.sql.SQLException: Cannot create PoolableConnectionFactory (Access denied for user 'root'@'localhost')

### ISSUE THREAD

**Issue by sadelax** [sadelax/ws#10]
tras el error _Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set #9_ me aparece Access denied for user 'root'

### **task list:**

- [x] usuario root en mysql activo, con contraseña satistactoriamente creada, en la base de datos 50_examen_banco
- [x] username y contraseña coinciden en el context.xml
- [x] all privileges granted para root en mysql en la bbdd con `CREATE USER 'sandra'@'%' IDENTIFIED BY 'contraseña_de_sandra';
`, `GRANT ALL PRIVILEGES ON *.* TO 'sandra'@'%' WITH GRANT OPTION;` y `FLUSH PRIVILEGES;`
- [x] reiniciar con sudo service mysql restar después de los cambios de permisos.
- [x] ./catalina.sh run satistactoriamente.
- [x] verificar el host y la conexión, @hostname: raspberrypi
- [x] probar desde el workbench.
- [ ] verificar la configuración de autenticación de mysql en /etc/mysql/mysql.conf.d/mysqld.cnf. supuestamente hay opciones como `bind-address`, `skip-networking` y `skip-grant-tables` que afectan a la conexión y los permisos.
- [ ] obtener logs de mysql tras el crash.

### **pasos para reproducir el error**

1. ./catalina.sh run
2. login ó registro de usuario (interactuar con la bbdd)

### **comportamiento esperado**
que aparezca el menú principal

### **comportamiento actual**
```
Type Exception Report

Message org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
	org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
	org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1626)
	org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1665)
	persistencia.UsuarioDaoJPA.valida(UsuarioDaoJPA.java:31)
	negocio.GestionUsuariosImpl.existe(GestionUsuariosImpl.java:15)
	vista.Controller.doPost(Controller.java:199)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:528)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:596)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
Root Cause

org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
	org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:111)
	org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:138)
	org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:50)
	org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:149)
	org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:176)
	org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:151)
	org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:2122)
	org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2059)
	org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2037)
	org.hibernate.loader.Loader.doQuery(Loader.java:956)
	org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:357)
	org.hibernate.loader.Loader.doList(Loader.java:2868)
	org.hibernate.loader.Loader.doList(Loader.java:2850)
	org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2682)
	org.hibernate.loader.Loader.list(Loader.java:2677)
	org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:540)
	org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:400)
	org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:218)
	org.hibernate.internal.SessionImpl.list(SessionImpl.java:1459)
	org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1649)
	org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1617)
	org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1665)
	persistencia.UsuarioDaoJPA.valida(UsuarioDaoJPA.java:31)
	negocio.GestionUsuariosImpl.existe(GestionUsuariosImpl.java:15)
	vista.Controller.doPost(Controller.java:199)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:528)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:596)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
Root Cause

java.sql.SQLException: Cannot create PoolableConnectionFactory (Access denied for user 'root'@'localhost')
	org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:632)
	org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:534)
	org.apache.tomcat.dbcp.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:710)
	org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
	org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:38)
	org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:108)
	org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:138)
	org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:50)
	org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:149)
	org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:176)
	org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:151)
	org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:2122)
	org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2059)
	org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2037)
	org.hibernate.loader.Loader.doQuery(Loader.java:956)
	org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:357)
	org.hibernate.loader.Loader.doList(Loader.java:2868)
	org.hibernate.loader.Loader.doList(Loader.java:2850)
	org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2682)
	org.hibernate.loader.Loader.list(Loader.java:2677)
	org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:540)
	org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:400)
	org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:218)
	org.hibernate.internal.SessionImpl.list(SessionImpl.java:1459)
	org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1649)
	org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1617)
	org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1665)
	persistencia.UsuarioDaoJPA.valida(UsuarioDaoJPA.java:31)
	negocio.GestionUsuariosImpl.existe(GestionUsuariosImpl.java:15)
	vista.Controller.doPost(Controller.java:199)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:528)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:596)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
Root Cause

java.sql.SQLException: Access denied for user 'root'@'localhost'
	com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:824)
	com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:444)
	com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237)
	com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	org.apache.tomcat.dbcp.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:52)
	org.apache.tomcat.dbcp.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:414)
	org.apache.tomcat.dbcp.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:112)
	org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:628)
	org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:534)
	org.apache.tomcat.dbcp.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:710)
	org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
	org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:38)
	org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:108)
	org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:138)
	org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:50)
	org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:149)
	org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:176)
	org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:151)
	org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:2122)
	org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2059)
	org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2037)
	org.hibernate.loader.Loader.doQuery(Loader.java:956)
	org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:357)
	org.hibernate.loader.Loader.doList(Loader.java:2868)
	org.hibernate.loader.Loader.doList(Loader.java:2850)
	org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2682)
	org.hibernate.loader.Loader.list(Loader.java:2677)
	org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:540)
	org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:400)
	org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:218)
	org.hibernate.internal.SessionImpl.list(SessionImpl.java:1459)
	org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1649)
	org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1617)
	org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1665)
	persistencia.UsuarioDaoJPA.valida(UsuarioDaoJPA.java:31)
	negocio.GestionUsuariosImpl.existe(GestionUsuariosImpl.java:15)
	vista.Controller.doPost(Controller.java:199)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:528)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:596)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)

```

**Comment by sadelax** [comment]
###  verificar el host y la conexión, @hostname: raspberrypi
```
mysql> SELECT INET_ATON(@@hostname);
+-----------------------+
| INET_ATON(@@hostname) |
+-----------------------+
|                  NULL |
+-----------------------+
1 row in set, 1 warning (0.00 sec)
```
###  probar desde el workbench.
Failed to Connect to MySQL at 192.168.1.136:3306 with user sandra. Unanle to connect to localhost
acabo de ver que el método de conexión: Standard (TCP/IP), pero también hay Standard (TCP/IP) over SSH 🤡

**Comment by sadelax** [comment]
he cambiado a MariaDB y funciona correctamente
